# Generated by Django 4.2.4 on 2023-11-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productdeliverylocation_product_and_more'),
        ('accounts', '0006_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressus',
            old_name='address_one',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='addressus',
            name='address_two',
        ),
        migrations.AddField(
            model_name='addressus',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.state'),
        ),
        migrations.AlterField(
            model_name='addressus',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.city'),
        ),
        migrations.AlterField(
            model_name='addressus',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.country'),
        ),
    ]
