# Generated by Django 4.2.4 on 2023-11-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdeliverylocation',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_countries',
            field=models.ManyToManyField(related_name='delivery_products', to='products.country'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.country')),
                ('sate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.state')),
            ],
        ),
        migrations.AddField(
            model_name='productdeliverylocation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.city'),
        ),
        migrations.AddField(
            model_name='productdeliverylocation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.state'),
        ),
    ]
